# Generated by Django 5.2.7 on 2025-10-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ser', models.CharField(max_length=100, verbose_name='Nombre')),
                ('desc', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('duracion', models.CharField(max_length=50, verbose_name='Duración')),
                ('tipo_de_serv', models.CharField(max_length=100, verbose_name='Tipo de Servicio')),
            ],
        ),
    ]
